<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Doka.EntityFrameworkCore.SafeMigrations.Sample</AssemblyName>
    <RootNamespace>Doka.EntityFrameworkCore.SafeMigrations.Sample</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Doka.EntityFrameworkCore.SafeMigrations\Doka.EntityFrameworkCore.SafeMigrations.csproj" />
    <ProjectReference Include="..\..\src\Doka.EntityFrameworkCore.SafeMigrations.MySql\Doka.EntityFrameworkCore.SafeMigrations.MySql.csproj" />
    <ProjectReference Include="..\..\src\Doka.EntityFrameworkCore.SafeMigrations.PostgreSql\Doka.EntityFrameworkCore.SafeMigrations.PostgreSql.csproj" />
  </ItemGroup>
</Project>
