<Project>
  <Target Name="AddDokaMySqlSafeMigrationsDesignTimeServicesReference"
          BeforeTargets="CoreGenerateAssemblyInfo"
          Condition="'@(PackageReference->WithMetadataValue('Identity', 'Microsoft.EntityFrameworkCore.Design'))' != ''
                     Or '@(PackageReference->WithMetadataValue('Identity', 'Microsoft.EntityFrameworkCore.Tools'))' != ''">
    <ItemGroup>
      <AssemblyAttribute Include="Microsoft.EntityFrameworkCore.Design.DesignTimeServicesReferenceAttribute">
        <_Parameter1>Doka.EntityFrameworkCore.SafeMigrations.MySql.MySqlSafeMigrationDesignTimeServices, Doka.EntityFrameworkCore.SafeMigrations.MySql</_Parameter1>
        <_Parameter2>Doka.EntityFrameworkCore.MySql</_Parameter2>
      </AssemblyAttribute>
    </ItemGroup>
  </Target>
</Project>
