<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Doka.EntityFrameworkCore.SafeMigrations.Benchmarks</AssemblyName>
    <RootNamespace>Doka.EntityFrameworkCore.SafeMigrations.Benchmarks</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Doka.EntityFrameworkCore.SafeMigrations\Doka.EntityFrameworkCore.SafeMigrations.csproj" />
  </ItemGroup>
</Project>
